import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { cn } from "@/lib/utils";

import TopSubscribe from "@/components/UI/Top-Subscribe/top-subscribe";
import { TopNavigationMenu } from "@/components/Layout/top-nav-menu";
import NavHeader from "@/components/Layout/nav-head";

export const metadata: Metadata = {
  title: "Luo Patisserie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={cn(GeistSans.variable)}>
        <div className="absolute inset-x-0 top-0">
          <TopSubscribe />
          <NavHeader />
          {/* <TopNavigationMenu /> */}
        </div>
        {children}
      </body>
    </html>
  );
}
