export const items = [
  {
    id: 1,
    name: "Blueberry Cheesecake",
    price: 70000,
    imgRef: "/assets/dummy/Lou_Pastry_15.jpg",
    is_new_arrival: true,
    is_bestseller: false,
    category: "Fruit-based",
  },
  {
    id: 2,
    name: "Cake 2",
    price: 180000,
    imgRef: "/assets/dummy/Lou_Pastry_2.jpg",
    is_new_arrival: false,
    is_bestseller: true,
    category: "Fruit-based",
  },
  {
    id: 3,
    name: "Blueberry Cheesecake 3",
    price: 100000,
    imgRef: "/assets/dummy/Lou_Pastry_15.jpg",
    is_new_arrival: true,
    is_bestseller: false,
    category: "Fruit-based",
  },
  {
    id: 4,
    name: "Luo F&B 36",
    price: 50000,
    imgRef: "/assets/dummy/Lou_F&B_36.jpg",
    is_new_arrival: true,
    is_bestseller: true,
    category: "Fruit-based",
  },
  {
    id: 5,
    name: "Strawberry Cake",
    price: 50000,
    imgRef: "/assets/dummy/Lou_Pastry_10.jpg",
    is_new_arrival: false,
    is_bestseller: true,
    category: "Fruit-based",
  },
  {
    id: 6,
    name: "Luo F&B 51",
    price: 50000,
    imgRef: "/assets/dummy/Lou_F&B_51.jpg",
    is_new_arrival: false,
    is_bestseller: true,
    category: "Nut-free",
  },
  {
    id: 7,
    name: "Luo F&B 69",
    price: 50000,
    imgRef: "/assets/dummy/Lou_F&B_69.jpg",
    is_new_arrival: false,
    is_bestseller: true,
    category: "Nut-free",
  },
  {
    id: 8,
    name: "Blueberry Cheesecake 4",
    price: 100000,
    imgRef: "/assets/dummy/Lou_Pastry_15.jpg",
    is_new_arrival: true,
    is_bestseller: false,
    category: "Nut-free",
  },
  {
    id: 9,
    name: "Blueberry Cheesecake 5",
    price: 100000,
    imgRef: "/assets/dummy/Lou_Pastry_15.jpg",
    is_new_arrival: true,
    is_bestseller: false,
    category: "Nut-free",
  },
  {
    id: 10,
    name: "Blueberry Cheesecake 6",
    price: 100000,
    imgRef: "/assets/dummy/Lou_Pastry_15.jpg",
    is_new_arrival: true,
    is_bestseller: false,
    category: "Nut-free",
  },
  {
    id: 11,
    name: "Blueberry Cheesecake 6",
    price: 100000,
    imgRef: "/assets/dummy/Lou_Pastry_15.jpg",
    is_new_arrival: true,
    is_bestseller: false,
    category: "Gelatine-free",
  },
  {
    id: 12,
    name: "Blueberry Cheesecake 6",
    price: 100000,
    imgRef: "/assets/dummy/Lou_Pastry_15.jpg",
    is_new_arrival: true,
    is_bestseller: false,
    category: "Gelatine-free",
  },
];
